In [1]:
import cv2
import numpy as np

# Load the image
img = cv2.imread('squares.jpg')

# Convert the image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Adjust the Canny edge detection thresholds
low_threshold = 50
high_threshold = 150
edges = cv2.Canny(gray, low_threshold, high_threshold, apertureSize=3)

# Find contours in the image
contours, hierarchy = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Initialize an empty list to store the coordinates of the squares
squares = []

# Loop through the contours
for cnt in contours:
        # Approximate the contour with a polygon
        approx = cv2.approxPolyDP(cnt, 0.01 * cv2.arcLength(cnt, True), True)
        # If the polygon has four vertices and is convex, it could be a rectangle
        if len(approx) == 4 and cv2.isContourConvex(approx):
            # Calculate the bounding box of the polygon
            x, y, w, h = cv2.boundingRect(approx)
            # Draw a green rectangle around the rectangle
            cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)

            # Add the coordinates of the rectangle to the list
            squares.append((x, y, x+w, y+h))

# Sort the squares from left to right and top to bottom
squares = sorted(squares, key=lambda x: (x[1], x[0]))

# Initialize a 3x3 grid of zeros to represent the tic tac toe board
board = np.zeros((3, 3), dtype=np.int)

# Loop through the squares and fill in the corresponding cell of the grid
for i, square in enumerate(squares):
    row = i // 3
    col = i % 3
    x1, y1, x2, y2 = square
    # Draw a green rectangle around the square
    cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
    # Add the square to the grid
    board[row, col] = 1 if i % 2 == 0 else 2

# Print the grid
print(board)

# Display the image
cv2.imshow('Squares', img)
cv2.waitKey(0)
cv2.destroyAllWindows()




<ipython-input-1-5f7548e93fe1>:39: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  board = np.zeros((3, 3), dtype=np.int)


[[1 2 1]
 [2 1 2]
 [1 2 0]]
